# Generated by Django 5.2.4 on 2025-08-18 10:56

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='image_public_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_public_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_public_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='banner_image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/'),
        ),
    ]
