# Generated by Django 5.2.4 on 2025-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_day_image_public_url_gallery_image_public_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpoint',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
