# Generated by Django 5.2.4 on 2025-08-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_alter_featuredpoint_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
