# Generated by Django 5.2.4 on 2025-08-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_itinerary_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='day',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
