# Generated by Django 5.2.4 on 2025-08-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0005_alter_day_options_day_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
