# Generated by Django 5.2.4 on 2025-09-02 10:37

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0007_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('banner_image', models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='destinations/')),
                ('icon', models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='destinations/')),
                ('banner_image_public_url', models.URLField(blank=True, null=True)),
                ('icon_public_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
