# Generated by Django 5.2.4 on 2025-09-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0010_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itinerary.categories'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itinerary.collections'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itinerary.countries'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itinerary.destinations'),
        ),
    ]
