# Generated by Django 5.2.4 on 2025-09-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0011_remove_itinerary_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
