# Generated by Django 5.2.4 on 2025-09-04 04:42

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0012_itinerary_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/gallery'),
        ),
    ]
