# Generated by Django 5.2.4 on 2025-09-04 04:48

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0013_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='banner_image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='collections/banners'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='collections/icons'),
        ),
        migrations.AlterField(
            model_name='day',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/places'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='banner_image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='destinations/banners'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='icon',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='destinations/icons'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/hotels'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='banner_image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='itinerary/banner'),
        ),
    ]
