# Generated by Django 5.2.4 on 2025-09-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0014_alter_collections_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='general_rating',
            field=models.FloatField(default=5),
        ),
    ]
