# Generated by Django 5.2.4 on 2025-09-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0015_itinerary_general_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
