# Generated by Django 5.2.4 on 2025-09-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0016_gallery_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='popular_destinations',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
