# Generated by Django 5.2.4 on 2025-09-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0017_collections_popular_destinations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='popular_destinations',
            new_name='popular_journeys',
        ),
    ]
