# Generated by Django 5.2.4 on 2025-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0019_alter_day_title_alter_destinationhighlight_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
