# Generated by Django 5.2.4 on 2025-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0020_day_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='popular_journeys',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
