# Generated by Django 5.2.4 on 2025-09-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0021_destinations_popular_journeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
