# Generated by Django 5.2.4 on 2025-09-23 04:33

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0022_itinerary_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='cruise/destinations')),
                ('image_public_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
