# Generated by Django 5.2.4 on 2025-09-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0023_cruisedestination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CruiseDestination',
            new_name='CruiseDeals',
        ),
    ]
