# Generated by Django 5.2.4 on 2025-09-23 06:03

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0024_rename_cruisedestination_cruisedeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisedeals',
            name='image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='cruise/deals'),
        ),
    ]
