# Generated by Django 5.2.4 on 2025-09-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0025_alter_cruisedeals_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruisedeals',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
