# Generated by Django 5.2.4 on 2025-09-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0026_cruisedeals_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruisedeals',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
