# Generated by Django 5.2.4 on 2025-07-27 07:08

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(storage=storages.backends.s3.S3Storage(bucket_name='mybucket', endpoint_url='https://f30c97b5e92eb15944ca7c0536b63e54.r2.cloudflarestorage.com'), upload_to='uploads/')),
            ],
        ),
    ]
