# Generated by Django 5.2.4 on 2025-08-03 09:41

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.FileField(storage=storages.backends.s3.S3Storage(bucket_name='mybucket', endpoint_url='https://pub-c75e3733f0bd4a078b015afdd3afc354.r2.dev/mybucket/'), upload_to='uploads/'),
        ),
    ]
