# Generated by Django 5.2.4 on 2025-08-03 09:42

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_blogpost_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.FileField(storage=storages.backends.s3.S3Storage(bucket_name='mybucket', endpoint_url='https://f30c97b5e92eb15944ca7c0536b63e54.r2.cloudflarestorage.com/mybucket'), upload_to='uploads/'),
        ),
    ]
