# Generated by Django 5.2.4 on 2025-08-03 09:48

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_blogpost_preview_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.FileField(storage=blueterra.storages_backends.R2PublicStorage(), upload_to='uploads/'),
        ),
    ]
