# Generated by Django 5.2.4 on 2025-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_delete_product_alter_blogpost_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_public_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
