# Generated by Django 5.2.4 on 2025-09-04 04:57

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_blogpost_image_public_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.FileField(storage=blueterra.storages_backends.R2PublicStorage(), upload_to='blogs/'),
        ),
    ]
