# Generated by Django 5.2.4 on 2025-09-11 10:02

import blueterra.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_alter_blogpost_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.FileField(blank=True, null=True, storage=blueterra.storages_backends.R2PublicStorage(), upload_to='blogs/'),
        ),
    ]
